version: '3.1'

services:

  db:
    image: icorrea/postgresql:11.7-alpine3.11

    environment:
      POSTGRES_PASSWORD: senha123
      POSTGRES_USER: userufs
      POSTGRES_DB: ufsdb
    networks:
      - icorrea_net
    volumes:
      - ~/svr/postgresql/ufs-akka-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "italiviocorrea@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "senha123"
    ports:
      - 8181:80
    depends_on:
      - db
    networks:
      - icorrea_net

networks:
  icorrea_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.48.0.0/16